github.com:
    users:
        FedeBrus:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: FedeBrus
