[window]
	opacity = 1
	padding = { x = 4, y = 4 }
	startup_mode = "Maximized"

[font]
	normal = { family = "Iosevka Nerd Font", style = "Regular" }
	bold = { family = "Iosevka Nerd Font", style = "Bold" }
	italic = { family = "Iosevka Nerd Font", style = "Italic" }
	bold_italic = { family = "Iosevka Nerd Font", style = "Bold Italic" }

	size = 11

[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]
	
